### ISSUE TITLE
to- - Filtris võiks olla järgnevad väljad:  Case nr Case type Judge name Registration

### ISSUE THREAD

**Issue by kokakoola** [kokakoola/cis#12]
**Sender**: jaak.laanpere@netgroup.ee
[Open #18 in Usersnap Dashboard](https://usersnap.com/a/#/cis/p/cis/18)
**Notes**:
- (1) Filtris võiks olla järgnevad väljad:

Case nr
Case type
Judge name
Registration date range 
- (2) Pole vaja neid nuppe.

![to- - Filtris võiks olla järgnevad väljad:  Case nr Case type Judge name Registration](https://usersnappublic.s3.amazonaws.com/2015-01-16/11-10/4e688969-6539-461a-9252-cb96ed81ec13.png)

**Browser**: Chrome 39 (Windows 8.1)
**Referer**: [http://hammr.co/3893879/13/registry.html](http://hammr.co/3893879/13/registry.html)
**IP**: 213.180.4.188
**Screen size**: 1280 x 800 **Browser size**: 1280 x 639

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by akonga** [comment]
Nõus. Date range peaks koosnema kahest tekstikastist (start - end). Mõlemal datepicker.
