### ISSUE TITLE
to- - Documendi lisamiseks tuleks teha alamvorm, sest sellisel moel jääb segaseks, kas

### ISSUE THREAD

**Issue by kokakoola** [kokakoola/cis#16]
**Sender**: jaak.laanpere@netgroup.ee
[Open #22 in Usersnap Dashboard](https://usersnap.com/a/#/cis/p/cis/22)
**Notes**:
- (1) Documendi lisamiseks tuleks teha alamvorm, sest sellisel moel jääb segaseks, kas iga üleslaetav fail on dokument ja jäävad ka metaandmed (title, type, ...) külge panemata.

Dokumendi alavormi mock ja kirjeldus on OneNote'is olemas. Sinu valida, kas teha folditav või pop-up või mõni muu äge teema.

![to- - Documendi lisamiseks tuleks teha alamvorm, sest sellisel moel jääb segaseks, kas](https://usersnappublic.s3.amazonaws.com/2015-01-16/12-03/2ffa6b41-4a33-4547-b9c3-3672f83deaef.png)

**Browser**: Chrome 39 (Windows 8.1)
**Referer**: [http://hammr.co/3893879/13/registry.html](http://hammr.co/3893879/13/registry.html)
**IP**: 213.180.4.188
**Screen size**: 1920 x 1200 **Browser size**: 1858 x 1036

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by akonga** [comment]
Nõus Jaaguga, metaandmestik peab olema küljes. (OneNote)
