### ISSUE TITLE
bin kaustade ümbrenimetamine

### ISSUE THREAD

**Issue by Naninunnadi** [kokakoola/cis#3]
Hei, palun nimeta bin kaustad ümber millekski muuks kui "bin", vastasel korral solutioni lisades ei saa browseris neile ligi ja peame eraldi erandid nende kasutade pathide kohta kirjutama juurdepääsu lubamiseks.

**Comment by kokakoola** [comment]
eemaldatud. kui tagasi ilmub, anna palun märku
